Saving work in progress

diff --git a/bin/process-requests b/bin/process-requests
--- a/bin/process-requests
+++ b/bin/process-requests
@@ -5,7 +5,7 @@ REQDIR=$1
 COUNT=$2
 REQUEST_ID="`date +%Y%m%d`-$((COUNT+1))-`date +%H%M`"
 
-ATTACHDIR="$REQDIR/$REQUEST_ID/attachments"
+ATTACHDIR="${REQDIR}/${REQUEST_ID}/attachments"
 LICENSE_TOOL=/data/vivipos_sdk/DONTRELEASE/getSystemLicense
 SMTP_CLIENT=msmtp
 REPLY_SENDER="VIVIPOS License Service"
@@ -30,31 +30,31 @@ validate_stub()
     local STUB=$3
     local KEY=$4
 
-    if [ -z "$ORDER" ]; then
+    if [ -z "${ORDER}" ]; then
 	REASON="Order number is empty"
 	return 1
     else
-	PREFIX=`echo -n $ORDER | awk -F"-" '{print $1}'`
-	if [ "$PREFIX" != "B220" -a "$PREFIX" != "V220" -a "$PREFIX" != "VM" ]; then
+	local PREFIX=`echo -n ${ORDER} | awk -F"-" '{print $1}'`
+	if [ "${PREFIX}" != "B220" -a "${PREFIX}" != "V220" -a "${PREFIX}" != "VM" ]; then
 	    REASON="Invalid order number"
 	    return 1
 	fi
     fi
 
-    if [ "$PREFIX" = "VM" -a -z "$SERIAL" ]; then
+    if [ "${PREFIX}" = "VM" -a -z "${SERIAL}" ]; then
 	REASON="Serial number is empty for non-VM license"
 	return 1
     fi
 
-    STUB_LEN=`echo -n $STUB | wc -c`
-    if [ $STUB_LEN -ne 128 ]; then
-	REASON="License stub key length is not 128 bytes ($STUB_LEN)"
+    local STUB_LEN=`echo -n ${STUB} | wc -c`
+    if [ ${STUB_LEN} -ne 128 ]; then
+	REASON="Terminal stub length is not 128 bytes (${STUB_LEN})"
 	return 1
     fi
 
-    KEY_LEN=`echo -n $KEY | wc -c`
-    if [ $KEY_LEN -ne 128 ]; then
-	REASON="License key length is not 128 bytes ($KEY_LEN)"
+    KEY_LEN=`echo -n ${KEY} | wc -c`
+    if [ ${KEY_LEN} -ne 128 ]; then
+	REASON="License key length is not 128 bytes (${KEY_LEN})"
 	return 1
     fi
 
@@ -63,30 +63,30 @@ validate_stub()
 
 ############################################################################
 #
-# store_license
+# store_stub
 #
-# store license in db
+# store terminal stub/license in db
 #
 # @args: <stub file>
 #
 ############################################################################
 
 SDK_PARTNER_ID=VIVIPOS_SDK
-store_license() {
+store_stub() {
 
 # insert entry into Terminals
-cat | mysql vivipos <<EOF-$REQUEST_ID
+cat | mysql vivipos <<EOF-${REQUEST_ID}
 INSERT into Terminals(terminal_stub, serial_number, dallas_key, system_name, vendor_name, mac_address, model, created_by, created, create_request_id)
-values ('$license_stub', '$SERIAL', '$dallas', '$system_name', '$vendor_name', '$mac_address', '', '$REQ_TO', NOW(), '$REQUEST_ID')
-ON DUPLICATE KEY UPDATE model=VALUES(model), serial_number=VALUES(serial_number), created_by=VALUES(created_by), create_request_id='$REQUEST_ID', update_count=update_count+1
-EOF-$REQUEST_ID
+values ('${license_stub}', '${SERIAL}', '${dallas}', '${system_name}', '${vendor_name}', '${mac_address}', '', '${REQ_TO}', NOW(), '${REQUEST_ID}')
+ON DUPLICATE KEY UPDATE model=VALUES(model), serial_number=VALUES(serial_number), created_by=VALUES(created_by), create_request_id='${REQUEST_ID}', update_count=update_count+1
+EOF-${REQUEST_ID}
 
 # insert license
-cat | mysql vivipos <<EOF-$REQUEST_ID
+cat | mysql vivipos <<EOF-${REQUEST_ID}
 INSERT into Licenses(terminal_stub, partner_id, license_key, order_number, signed_by, created_by, created, create_request_id)
-values ('$license_stub', '$SDK_PARTNER_ID', '$KEY', '$ORDER_NO', '$SENDER', '$REQ_TO', NOW(), '$REQUEST_ID')
-ON DUPLICATE KEY UPDATE license_key=VALUES(license_key), signed_by=VALUES(signed_by), created_by=VALUES(created_by), create_request_id='$REQUEST_ID', update_count=update_count+1
-EOF-$REQUEST_ID
+values ('${license_stub}', '${SDK_PARTNER_ID}', '${KEY}', '${ORDER_NO}', '${SENDER}', '${REQ_TO}', NOW(), '${REQUEST_ID}')
+ON DUPLICATE KEY UPDATE license_key=VALUES(license_key), signed_by=VALUES(signed_by), created_by=VALUES(created_by), create_request_id='${REQUEST_ID}', update_count=update_count+1
+EOF-${REQUEST_ID}
 
 }
 
@@ -105,102 +105,102 @@ process_stub() {
     local stub=$1
 
     # for each stub file, file name is the serial number
-    SERIAL=`basename "$stub" .txt`
+    SERIAL=`basename "${stub}" .txt`
 
     # import stub details into environment
-    eval `awk -F"=" '$1 ~ /[A-Za-z0-9_]+/ { print "export " $1 "=\"" $2 "\"";  }' "$stub"`
+    eval `awk -F"=" '$1 ~ /[A-Za-z0-9_]+/ { print "export " $1 "=\"" $2 "\"";  }' "${stub}"`
 
     # generate license key
-    KEY=`$LICENSE_TOOL -f "$stub"`
+    KEY=`${LICENSE_TOOL} -f "${stub}"`
 
     # log output
-    cat > "${REQDIR}/${REQUEST_ID}/stub-${SERIAL}" <<EOF-$REQUEST_ID
-ORDER_NO=$ORDER_NO
-SERIAL_NUMBER=$SERIAL
-DALLAS_KEY=$dallas
-SYSTEM_NAME=$system_name
-VENDOR_NAME=$vendor_name
-MAC_ADDRESS=$mac_address
-TERMINAL_STUB=$license_stub
-SDK_LICENSE_KEY=$KEY
-EOF-$REQUEST_ID
+    cat > "${REQDIR}/${REQUEST_ID}/stub-${SERIAL}" <<EOF-${REQUEST_ID}
+ORDER_NO=${ORDER_NO}
+SERIAL_NUMBER=${SERIAL}
+DALLAS_KEY=${dallas}
+SYSTEM_NAME=${system_name}
+VENDOR_NAME=${vendor_name}
+MAC_ADDRESS=${mac_address}
+TERMINAL_STUB=${license_stub}
+SDK_LICENSE_KEY=${KEY}
+EOF-${REQUEST_ID}
 
     # are data valid?
-    validate_stub "$ORDER_NO" "$SERIAL" "$license_stub" "$KEY"
+    validate_stub "${ORDER_NO}" "${SERIAL}" "${license_stub}" "${KEY}"
     if [ "$?" -ne 0 ]; then
-        echo "ORDER <$ORDER_NO> FILE <$SERIAL> TYPE <STUB> REASON <$REASON>" >> "$REQDIR/$REQUEST_ID/rejected.log"
+        echo "ORDER <${ORDER_NO}> FILE <${SERIAL}> TYPE <STUB> REASON <${REASON}>" >> "${REQDIR}/${REQUEST_ID}/rejected.log"
         mv "${REQDIR}/${REQUEST_ID}/stub-${SERIAL}" "${REQDIR}/${REQUEST_ID}/bad-stub-${SERIAL}"
         return 1
     else
 
         # attempt to insert into DB
-        store_license
+        store_stub
         if [ "$?" -ne 0 ]; then
-            echo "ORDER <$ORDER_NO> FILE <$SERIAL> TYPE <STUB> REASON <$REASON>" >> "$REQDIR/$REQUEST_ID/rejected.log"
+            echo "ORDER <${ORDER_NO}> FILE <${SERIAL}> TYPE <STUB> REASON <${REASON}>" >> "${REQDIR}/${REQUEST_ID}/rejected.log"
             mv "${REQDIR}/${REQUEST_ID}/stub-${SERIAL}" "${REQDIR}/${REQUEST_ID}/failed-stub-${SERIAL}"
             return 1
         else
-            echo "ORDER <$ORDER_NO> FILE <$SERIAL> TYPE <STUB>" >> "$REQDIR/$REQUEST_ID/imported.log"
+            echo "ORDER <${ORDER_NO}> FILE <${SERIAL}> TYPE <STUB>" >> "${REQDIR}/${REQUEST_ID}/imported.log"
         fi
 
     fi
 }
 
 # saving request
-mkdir -p "$ATTACHDIR"
-env > "$REQDIR/$REQUEST_ID/env"
-cat > "$REQDIR/$REQUEST_ID/req"
+mkdir -p "${ATTACHDIR}"
+env > "${REQDIR}/${REQUEST_ID}/env"
+cat > "${REQDIR}/${REQUEST_ID}/req"
 
 # extract SUBJECT
-REQ_SUBJECT=`grep -E -m 1 -e "^Subject: " "$REQDIR/$REQUEST_ID/req"`
-REQ_TO=`grep -E -m 1 -e "^Delivered-To: " "$REQDIR/$REQUEST_ID/req" | awk -F" " '{print $2}'`
-REQ_DATE=`grep -E -m 1 -e "^Date: " "$REQDIR/$REQUEST_ID/req"`
-REQ_BODY=`sed '1,/^$/d' "$REQDIR/$REQUEST_ID/req"`
-REQ_CONTENT_TYPE=`grep -E -m 1 -e "^Content-Type: " "$REQDIR/$REQUEST_ID/req"`
+REQ_SUBJECT=`grep -E -m 1 -e "^Subject: " "${REQDIR}/${REQUEST_ID}/req"`
+REQ_TO=`grep -E -m 1 -e "^Delivered-To: " "${REQDIR}/${REQUEST_ID}/req" | awk -F" " '{print $2}'`
+REQ_DATE=`grep -E -m 1 -e "^Date: " "${REQDIR}/${REQUEST_ID}/req"`
+REQ_BODY=`sed '1,/^$/d' "${REQDIR}/${REQUEST_ID}/req"`
+REQ_CONTENT_TYPE=`grep -E -m 1 -e "^Content-Type: " "${REQDIR}/${REQUEST_ID}/req"`
 
 # extract multipart boundary
-REQ_MULTIPART_BOUNDARY=`echo $REQ_CONTENT_TYPE | sed -n '/^Content-Type: multipart\/mixed; / {
+REQ_MULTIPART_BOUNDARY=`echo ${REQ_CONTENT_TYPE} | sed -n '/^Content-Type: multipart\/mixed; / {
 s_.*boundary=\(.*\)_\1_
 p
 }'`
 
-if [ -z "$REQ_MULTIPART_BOUNDARY" ]; then
+if [ -z "${REQ_MULTIPART_BOUNDARY}" ]; then
     RES_MULTIPART_BOUNDARY=`uuid`
 else
-    RES_MULTIPART_BOUNDARY="$REQ_MULTIPART_BOUNDARY"
+    RES_MULTIPART_BOUNDARY="${REQ_MULTIPART_BOUNDARY}"
 fi
 
 # extract sender from request
-SENDER=`sed '/^Reply-To:/q; /^From:/h; /./d;g;q' "$REQDIR/$REQUEST_ID/req" | sed 's/ *(.*)//; s/>.*//; s/.*[:<] *//'`
-if [ -z "$SENDER" ]; then
-    SENDER=$FROM
+SENDER=`sed '/^Reply-To:/q; /^From:/h; /./d;g;q' "${REQDIR}/${REQUEST_ID}/req" | sed 's/ *(.*)//; s/>.*//; s/.*[:<] *//'`
+if [ -z "${SENDER}" ]; then
+    SENDER=${FROM}
 fi
 
 # extract attachments
-ripmime -i "$REQDIR/$REQUEST_ID/req" -d "$ATTACHDIR" --no-nameless
+ripmime -i "${REQDIR}/${REQUEST_ID}/req" -d "${ATTACHDIR}" --no-nameless
 
 # begin processing RAR attachments
-for f in `ls $ATTACHDIR/*.rar`; do
+for f in `ls ${ATTACHDIR}/*.rar`; do
 
     # for RAR, file name is the order number
     ORDER_NO=`basename "$f" .rar`
 
     # extract stub files into temp folder
-    mkdir "$ATTACHDIR/$ORDER_NO"
-    unrar x -y "$f" "$ATTACHDIR/$ORDER_NO"
+    mkdir "${ATTACHDIR}/${ORDER_NO}"
+    unrar x -y "$f" "${ATTACHDIR}/${ORDER_NO}"
 
-    for stub in `ls "$ATTACHDIR/$ORDER_NO"/*.txt`; do
-        process_stub "$stub"
+    for stub in `ls "${ATTACHDIR}/${ORDER_NO}"/*.txt`; do
+        process_stub "${stub}"
 
         STUB_RESULT=$?
 
         # processing corresponding LIC attachments (partner licenses)
-        SERIAL=`basename "$stub" .txt`
+        SERIAL=`basename "${stub}" .txt`
         if [ -f "${SERIAL}.lic" ]; then
-            if [ $STUB_RESULT -ne 0 ]; then
-                echo "ORDER <$ORDER_NO> FILE <$SERIAL> TYPE <PARTNER> REASON <Processing of terminal stub failed>" >> "$REQDIR/$REQUEST_ID/rejected.log"
+            if [ ${STUB_RESULT} -ne 0 ]; then
+                echo "ORDER <${ORDER_NO}> FILE <${SERIAL}> TYPE <PARTNER> REASON <Processing of terminal stub failed>" >> "${REQDIR}/${REQUEST_ID}/rejected.log"
             else
-                process_lic "${SERIAL}.lic"
+                process_license "${SERIAL}.lic"
             fi
         fi
     done
@@ -208,88 +208,93 @@ for f in `ls $ATTACHDIR/*.rar`; do
 done
 
 # begin processing TXT attachments (
-for stub in `ls $ATTACHDIR/*.txt`; do
+for stub in `ls ${ATTACHDIR}/*.txt`; do
 
     # for TXT, order number should be in the subject line
-    ORDER_NO=`echo $REQ_SUBJECT | grep -E -m 1 -e "^Subject: [ \t]*(B220|V220|VM)-[alnum]*" | awk -F" " '{print $2}'`
-    process_stub "$stub"
+    ORDER_NO=`echo ${REQ_SUBJECT} | grep -E -m 1 -e "^Subject: [ \t]*(B220|V220|VM)-[alnum]*" | awk -F" " '{print $2}'`
+    process_stub "${stub}"
 
     STUB_RESULT=$?
 
     # processing corresponding LIC attachments (partner licenses)
-    SERIAL=`basename "$stub" .txt`
+    SERIAL=`basename "${stub}" .txt`
     if [ -f "${SERIAL}.lic" ]; then
-        if [ $STUB_RESULT -ne 0 ]; then
-            echo "ORDER <$ORDER_NO> FILE <$SERIAL> TYPE <PARTNER> REASON <Processing of terminal stub failed>" >> "$REQDIR/$REQUEST_ID/rejected.log"
+        if [ ${STUB_RESULT} -ne 0 ]; then
+            echo "ORDER <${ORDER_NO}> FILE <${SERIAL}> TYPE <PARTNER> REASON <Processing of terminal stub failed>" >> "${REQDIR}/${REQUEST_ID}/rejected.log"
         else
-            process_lic "${SERIAL}.lic"
+            process_license "${SERIAL}.lic"
         fi
     fi
 done
 
 
 # prepare response
-cat > "$REQDIR/$REQUEST_ID/response" <<EOF-$REQUEST_ID
-From: $REPLY_SENDER
-To: $SENDER
-Subject: $REPLY_SUBJECT
-Reply-To: $REPLY_REPLY_TO
-Content-Type: multipart/mixed; boundary=$RES_MULTIPART_BOUNDARY
+cat > "${REQDIR}/${REQUEST_ID}/response" <<EOF-${REQUEST_ID}
+From: ${REPLY_SENDER}
+To: ${SENDER}
+Subject: ${REPLY_SUBJECT}
+Reply-To: ${REPLY_REPLY_TO}
+Content-Type: multipart/mixed; boundary=${RES_MULTIPART_BOUNDARY}
 
---$RES_MULTIPART_BOUNDARY
+--${RES_MULTIPART_BOUNDARY}
 Content-Type: text/plain; charset=utf-8
 Content-Transfer-Encoding: 7bit
 
 We have received and processed your license import request.
 Your request has been assigned the following ID:
 
-    $REQUEST_ID
+    ${REQUEST_ID}
 
 Results from your request:
 
-EOF-$REQUEST_ID
+EOF-${REQUEST_ID}
 
-if [ -f "$REQDIR/$REQUEST_ID/imported.log" ]; then
-    echo "[IMPORTED]" >> "$REQDIR/$REQUEST_ID/response"
-    cat "$REQDIR/$REQUEST_ID/imported.log" >> "$REQDIR/$REQUEST_ID/response"
-    echo >> "$REQDIR/$REQUEST_ID/response"
-    echo >> "$REQDIR/$REQUEST_ID/response"
+if [ -f "${REQDIR}/${REQUEST_ID}/imported.log" ]; then
+    echo "[IMPORTED]" >> "${REQDIR}/${REQUEST_ID}/response"
+    cat "${REQDIR}/${REQUEST_ID}/imported.log" >> "${REQDIR}/${REQUEST_ID}/response"
+    echo >> "${REQDIR}/${REQUEST_ID}/response"
+    echo >> "${REQDIR}/${REQUEST_ID}/response"
 fi
 
-if [ -f "$REQDIR/$REQUEST_ID/rejected.log" ]; then
-    echo "[REJECTED]" >> "$REQDIR/$REQUEST_ID/response"
-    cat "$REQDIR/$REQUEST_ID/rejected.log" >> "$REQDIR/$REQUEST_ID/response"
-    echo >> "$REQDIR/$REQUEST_ID/response"
-    echo >> "$REQDIR/$REQUEST_ID/response"
+if [ -f "${REQDIR}/${REQUEST_ID}/rejected.log" ]; then
+    echo "[REJECTED]" >> "${REQDIR}/${REQUEST_ID}/response"
+    cat "${REQDIR}/${REQUEST_ID}/rejected.log" >> "${REQDIR}/${REQUEST_ID}/response"
+    echo >> "${REQDIR}/${REQUEST_ID}/response"
+    echo >> "${REQDIR}/${REQUEST_ID}/response"
 fi
 
-if [ ! -f "$REQDIR/$REQUEST_ID/imported.log" -a ! -f "$REQDIR/$REQUEST_ID/rejected.log" ]; then
-    echo "-- No valid license file found --" >> "$REQDIR/$REQUEST_ID/response"
-    echo >> "$REQDIR/$REQUEST_ID/response"
-    echo >> "$REQDIR/$REQUEST_ID/response"
+if [ ! -f "${REQDIR}/${REQUEST_ID}/imported.log" -a ! -f "${REQDIR}/${REQUEST_ID}/rejected.log" ]; then
+    echo "-- No valid license file found --" >> "${REQDIR}/${REQUEST_ID}/response"
+    echo >> "${REQDIR}/${REQUEST_ID}/response"
+    echo >> "${REQDIR}/${REQUEST_ID}/response"
 fi
-echo "Yours Sincerely," >> "$REQDIR/$REQUEST_ID/response"
-echo "VIVIPOS License Service" >> "$REQDIR/$REQUEST_ID/response"
-echo >> "$REQDIR/$REQUEST_ID/response"
+echo "Yours Sincerely," >> "${REQDIR}/${REQUEST_ID}/response"
+echo "VIVIPOS License Service" >> "${REQDIR}/${REQUEST_ID}/response"
+echo >> "${REQDIR}/${REQUEST_ID}/response"
 
 # include original email
-cat >> "$REQDIR/$REQUEST_ID/response" <<EOF-$REQUEST_ID
+cat >> "${REQDIR}/${REQUEST_ID}/response" <<EOF-${REQUEST_ID}
 -------- Original Email --------
-From: $SENDER
-To: $REQ_TO
-Date: $REQ_DATE
-$REQ_SUBJECT
+From: ${SENDER}
+To: ${REQ_TO}
+Date: ${REQ_DATE}
+${REQ_SUBJECT}
 
---$RES_MULTIPART_BOUNDARY
-EOF-$REQUEST_ID
+--${RES_MULTIPART_BOUNDARY}
+EOF-${REQUEST_ID}
 
-if [ -z "$REQ_MULTIPART_BOUNDARY" ]; then
-echo "$REQ_CONTENT_TYPE" >> "$REQDIR/$REQUEST_ID/response"
-echo >> "$REQDIR/$REQUEST_ID/response"
+if [ -z "${REQ_MULTIPART_BOUNDARY}" ]; then
+echo "${REQ_CONTENT_TYPE}" >> "${REQDIR}/${REQUEST_ID}/response"
+echo >> "${REQDIR}/${REQUEST_ID}/response"
 fi
 
-cat >> "$REQDIR/$REQUEST_ID/response" <<EOF-$REQUEST_ID
-$REQ_BODY
-EOF-$REQUEST_ID
+cat >> "${REQDIR}/${REQUEST_ID}/response" <<EOF-${REQUEST_ID}
+${REQ_BODY}
+EOF-${REQUEST_ID}
 
-$SMTP_CLIENT -t < "$REQDIR/$REQUEST_ID/response" > "$REQDIR/$REQUEST_ID/response.smtp" 2>&1
+${SMTP_CLIENT} -t < "${REQDIR}/${REQUEST_ID}/response" > "${REQDIR}/${REQUEST_ID}/response.smtp" 2>&1
+if [ "$?" -ne 0 ]; then
+    mv "${REQDIR}/${REQUEST_ID}/response" "${REQDIR}/${REQUEST_ID}/response.unsent"
+else
+    mv "${REQDIR}/${REQUEST_ID}/response" "${REQDIR}/${REQUEST_ID}/response.sent"
+fi
